spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mcsm
    username: mcsm
    password: mcsm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect