spring:
  datasource:
    url: jdbc:h2:file:./data/mcinstaller
    username: mcinstaller
    password: mcinstaller
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    clear-checksums: false
    drop-first: false

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  paths-to-match: /**
  packages-to-scan: pl.bartlomiejstepien.mcsm.web.controller.rest
  swagger-ui:
    disable-swagger-default-url: true

servers-dir: servers
downloads-dir: downloads